from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List
import logging

logger = logging.getLogger(__name__)


class ReportGenerator:
    
    def __init__(self, project_path: Path):
        self.project_path = project_path
        self.issues_dir = project_path / 'issues'
        self.issues_dir.mkdir(exist_ok=True)
        logger.info(f"Reports will be saved to: {self.issues_dir}")
    
    def generate_file_report(self, analysis_result: Dict[str, Any]) -> Path:
        """
        Generate a markdown report for a single file analysis.
        
        Args:
            analysis_result: Dictionary containing analysis results
            
        Returns:
            Path to the generated report file
        """
        file_name = Path(analysis_result['file_name']).stem
        report_filename = f"{file_name}_report.md"
        report_path = self.issues_dir / report_filename
        
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        report_content = f"""# 🛡️ Sentinel Code Analysis Report

**File**: `{analysis_result['file_name']}`  
**Language**: {analysis_result['language']}  
**Analysis Date**: {timestamp}  
**Status**: {analysis_result['status'].upper()}

---

## 📊 Analysis Results

{analysis_result['analysis']}

---

## 📝 Notes

- This report was automatically generated by Sentinel Code Agent
- Review all CRITICAL and HIGH severity issues immediately
- Implement suggested fixes and best practices
- Re-run analysis after making changes to verify improvements

---

**Sentinel Code Agent** | Security & Code Quality Analysis
"""
        
        try:
            with open(report_path, 'w', encoding='utf-8') as f:
                f.write(report_content)
            logger.info(f"Report generated: {report_filename}")
            return report_path
        except Exception as e:
            logger.error(f"Error writing report for {analysis_result['file_name']}: {str(e)}")
            raise
    
    def generate_summary_report(self, summary_text: str) -> Path:
        """
        Generate a summary report for all analyzed files.
        
        Args:
            summary_text: Summary content
            
        Returns:
            Path to the summary report file
        """
        summary_path = self.issues_dir / 'SUMMARY.md'
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        report_content = f"""# 🛡️ Sentinel Code Analysis - Project Summary

**Analysis Date**: {timestamp}  
**Project**: {self.project_path.name}

---

{summary_text}

---

## 📂 Report Files

All individual file reports are located in the `issues/` directory.

---

**Sentinel Code Agent** | Automated Security Analysis
"""
        
        try:
            with open(summary_path, 'w', encoding='utf-8') as f:
                f.write(report_content)
            logger.info(f"Summary report generated: SUMMARY.md")
            return summary_path
        except Exception as e:
            logger.error(f"Error writing summary report: {str(e)}")
            raise
    
    def get_all_reports(self) -> List[Path]:
        """
        Get list of all report files in the issues directory.
        
        Returns:
            List of Path objects for report files
        """
        return list(self.issues_dir.glob('*.md'))
